spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/tricountapi-db
    username: sa
    password: 12

logging:
  level:
    org:
      .springframework.jdbc: debug
